language: java
install: true
jdk: openjdk8
before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
cache:
  directories:
  - $HOME/.gradle/caches/
  - $HOME/.gradle/wrapper/
  - $HOME/.sonar/cache/
before_script:
  - ./gradlew --no-daemon --version
script:
  - ./gradlew build
